default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: askmybook_development

test:
  <<: *default
  database: askmybook_test

production:
  <<: *default
  database: askmyboook_production
  username: askmybook
  password: <%= ENV['MYSITE_DATABASE_PASSWORD'] %>
  url: <%= ENV['DATABASE_URL'] %>
